<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('system_countries')->insert(['name'=>"Afghanistan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Albania", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Algeria", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"American Samoa", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Andorra", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Angola", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Anguilla", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Antarctica", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Antigua And Barbuda", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Argentina", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Armenia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Aruba", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Australia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Austria", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Azerbaijan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bahamas", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bahrain", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bangladesh", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Barbados", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Belarus", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Belgium", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Belize", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Benin", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bermuda", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bhutan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bolivia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bosnia And Herzegovina", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Botswana", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bouvet Island", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Brazil", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"British Indian Ocean Territory", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Brunei Darussalam", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Bulgaria", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Burkina Faso", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Burundi", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cambodia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cameroon", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Canada", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cape Verde", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cayman Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Central African Republic", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Chad", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Chile", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"China", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Christmas Island", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cocos (keeling) Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Colombia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Comoros", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Congo", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Congo, The Democratic Republic Of The", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cook Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Costa Rica", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cote D\'ivoire", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Croatia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cuba", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Cyprus", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Czech Republic", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Denmark", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Djibouti", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Dominica", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Dominican Republic", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"East Timor", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Ecuador", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Egypt", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"El Salvador", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Equatorial Guinea", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Eritrea", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Estonia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Ethiopia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Falkland Islands (malvinas)", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Faroe Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Fiji", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Finland", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"France", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"French Guiana", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"French Polynesia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"French Southern Territories", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Gabon", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Gambia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Georgia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Germany", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Ghana", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Gibraltar", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Greece", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Greenland", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Grenada", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Guadeloupe", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Guam", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Guatemala", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Guinea", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Guinea-bissau", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Guyana", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Haiti", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Heard Island And Mcdonald Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Holy See (vatican City State)", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Honduras", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Hong Kong", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Hungary", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Iceland", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"India", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Indonesia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Iran, Islamic Republic Of", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Iraq", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Ireland", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Israel", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Italy", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Jamaica", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Japan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Jordan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Kazakstan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Kenya", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Kiribati", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Korea, Democratic People\'s Republic Of", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Korea, Republic Of", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Kosovo", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Kuwait", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Kyrgyzstan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Lao People\'s Democratic Republic", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Latvia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Lebanon", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Lesotho", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Liberia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Libyan Arab Jamahiriya", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Liechtenstein", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Lithuania", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Luxembourg", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Macau", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Macedonia, The Former Yugoslav Republic Of", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Madagascar", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Malawi", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Malaysia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Maldives", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Mali", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Malta", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Marshall Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Martinique", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Mauritania", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Mauritius", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Mayotte", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Mexico", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Micronesia, Federated States Of", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Moldova, Republic Of", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Monaco", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Mongolia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Montserrat", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Montenegro", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Morocco", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Mozambique", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Myanmar", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Namibia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Nauru", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Nepal", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Netherlands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Netherlands Antilles", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"New Caledonia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"New Zealand", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Nicaragua", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Niger", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Nigeria", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Niue", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Norfolk Island", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Northern Mariana Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Norway", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Oman", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Pakistan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Palau", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Palestinian Territory, Occupied", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Panama", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Papua New Guinea", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Paraguay", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Peru", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Philippines", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Pitcairn", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Poland", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Portugal", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Puerto Rico", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Qatar", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Reunion", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Romania", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Russian Federation", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Rwanda", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Saint Helena", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Saint Kitts And Nevis", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Saint Lucia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Saint Pierre And Miquelon", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Saint Vincent And The Grenadines", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Samoa", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"San Marino", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Sao Tome And Principe", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Saudi Arabia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Senegal", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Serbia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Seychelles", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Sierra Leone", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Singapore", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Slovakia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Slovenia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Solomon Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Somalia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"South Africa", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"South Georgia And The South Sandwich Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Spain", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Sri Lanka", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Sudan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Suriname", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Svalbard And Jan Mayen", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Swaziland", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Sweden", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Switzerland", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Syrian Arab Republic", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Taiwan, Province Of China", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Tajikistan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Tanzania, United Republic Of", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Thailand", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Togo", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Tokelau", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Tonga", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Trinidad And Tobago", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Tunisia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Turkey", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Turkmenistan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Turks And Caicos Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Tuvalu", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Uganda", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Ukraine", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"United Arab Emirates", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"United Kingdom", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"United States", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"United States Minor Outlying Islands", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Uruguay", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Uzbekistan", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Vanuatu", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Venezuela", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Viet Nam", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Virgin Islands, British", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Virgin Islands, U.s.", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Wallis And Futuna", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Western Sahara", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Yemen", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Zambia", 'modified_by'=>1]);
		DB::table('system_countries')->insert(['name'=>"Zimbabwe", 'modified_by'=>1]);
    }
}
