<?php

use Illuminate\Database\Seeder;

class SystemIndustriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('system_industries')->insert(['name'=>"Abortion Policy/Anti-Abortion", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Abortion Policy/Pro-Abortion Rights", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Accountants", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Advertising/Public Relations", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Aerospace, Defense Contractors", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Agribusiness", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Agricultural Services & Products", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Agriculture", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Air Transport", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Air Transport Unions", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Airlines", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Alcoholic Beverages", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Alternative Energy Production & Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Architectural Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Attorneys/Law Firms", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Auto Dealers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Auto Dealers, Japanese", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Auto Manufacturers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Automotive", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Banking, Mortgage", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Banks, Commercial", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Banks, Savings & Loans", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Bars & Restaurants", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Beer, Wine & Liquor", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Books, Magazines & Newspapers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Broadcasters, Radio/TV", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Builders/General Contractors", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Builders/Residential", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Building Materials & Equipment", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Building Trade Unions ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Business Associations", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Business Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Cable & Satellite TV Production & Distribution", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Candidate Committees ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Candidate Committees, Democratic", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Candidate Committees, Republican", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Car Dealers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Car Dealers, Imports", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Car Manufacturers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Casinos / Gambling", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Cattle Ranchers/Livestock", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Chemical & Related Manufacturing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Chiropractors", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Civil Servants/Public Officials", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Clergy & Religious Organizations ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Clothing Manufacturing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Coal Mining", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Colleges, Universities & Schools", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Commercial Banks", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Commercial TV & Radio Stations", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Communications/Electronics", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Computer Software", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Conservative/Republican", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Construction", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Construction Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Construction Unions", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Credit Unions", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Crop Production & Basic Processing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Cruise Lines", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Cruise Ships & Lines", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Dairy", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Defense", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Defense Aerospace", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Defense Electronics", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Defense/Foreign Policy Advocates", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Democratic Candidate Committees ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Democratic Leadership PACs", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Democratic/Liberal ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Dentists", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Doctors & Other Health Professionals", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Drug Manufacturers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Education ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Electric Utilities", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Electronics Manufacturing & Equipment", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Electronics, Defense Contractors", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Energy & Natural Resources", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Entertainment Industry", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Environment ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Farm Bureaus", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Farming", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Finance / Credit Companies", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Finance, Insurance & Real Estate", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Food & Beverage", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Food Processing & Sales", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Food Products Manufacturing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Food Stores", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"For-profit Education", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Foreign & Defense Policy ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Forestry & Forest Products", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Foundations, Philanthropists & Non-Profits", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Funeral Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Gambling & Casinos", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Gambling, Indian Casinos", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Garbage Collection/Waste Management", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Gas & Oil", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Gay & Lesbian Rights & Issues", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"General Contractors", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Government Employee Unions", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Government Employees", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Gun Control ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Gun Rights ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Health", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Health Professionals", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Health Services/HMOs", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Hedge Funds", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"HMOs & Health Care Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Home Builders", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Hospitals & Nursing Homes", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Hotels, Motels & Tourism", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Human Rights ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Ideological/Single-Issue", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Indian Gaming", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Industrial Unions ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Insurance", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Internet", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Israel Policy", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Labor", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Lawyers & Lobbyists", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Lawyers / Law Firms", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Leadership PACs ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Liberal/Democratic", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Liquor, Wine & Beer", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Livestock", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Lobbyists", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Lodging / Tourism", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Logging, Timber & Paper Mills", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Manufacturing, Misc", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Marine Transport", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Meat processing & products", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Medical Supplies", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Mining", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Misc Business", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Misc Finance", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Misc Manufacturing & Distributing ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Misc Unions ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Miscellaneous Defense", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Miscellaneous Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Mortgage Bankers & Brokers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Motion Picture Production & Distribution", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Music Production", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Natural Gas Pipelines", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Newspaper, Magazine & Book Publishing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Non-profits, Foundations & Philanthropists", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Nurses", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Nursing Homes/Hospitals", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Nutritional & Dietary Supplements", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Oil & Gas", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Other", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Payday Lenders", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Pharmaceutical Manufacturing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Pharmaceuticals / Health Products", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Phone Companies", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Physicians & Other Health Professionals", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Postal Unions", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Poultry & Eggs", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Power Utilities", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Printing & Publishing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Private Equity & Investment Firms", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Pro-Israel ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Professional Sports, Sports Arenas & Related Equipment & Services", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Progressive/Democratic", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Public Employees", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Public Sector Unions ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Publishing & Printing", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Radio/TV Stations", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Railroads", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Real Estate", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Record Companies/Singers", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Recorded Music & Music Production", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Recreation / Live Entertainment", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Religious Organizations/Clergy", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Republican Candidate Committees ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Republican Leadership PACs", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Republican/Conservative ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Residential Construction", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Restaurants & Drinking Establishments", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Retail Sales", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Retired", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Savings & Loans", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Schools/Education", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Sea Transport", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Securities & Investment", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Special Trade Contractors", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Sports, Professional", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Steel Production ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Stock Brokers/Investment Industry", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Student Loan Companies", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Sugar Cane & Sugar Beets", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Teachers Unions", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Teachers/Education", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Telecom Services & Equipment", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Telephone Utilities", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Textiles ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Timber, Logging & Paper Mills", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Tobacco", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Transportation", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Transportation Unions ", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Trash Collection/Waste Management", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Trucking", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"TV / Movies / Music", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"TV Production", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions, Airline", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions, Building Trades", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions, Industrial", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions, Misc", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions, Public Sector", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions, Teacher", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Unions, Transportation", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Universities, Colleges & Schools", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Vegetables & Fruits", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Venture Capital", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Waste Management", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Wine, Beer & Liquor", 'modified_by'=>1]);
		DB::table('system_industries')->insert(['name'=>"Women's Issues ", 'modified_by'=>1]);
    }
}
