<?php

use Illuminate\Database\Seeder;

class SystemMajorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('system_majors')->insert(['name'=>"GENERAL AGRICULTURE", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"AGRICULTURE PRODUCTION AND MANAGEMENT", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"AGRICULTURAL ECONOMICS", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ANIMAL SCIENCES", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"FOOD SCIENCE", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PLANT SCIENCE AND AGRONOMY", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SOIL SCIENCE", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS AGRICULTURE", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"FORESTRY", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"NATURAL RESOURCES MANAGEMENT", 'category'=>"Agriculture & Natural Resources", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"FINE ARTS", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"DRAMA AND THEATER ARTS", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MUSIC", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"VISUAL AND PERFORMING ARTS", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMMERCIAL ART AND GRAPHIC DESIGN", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"FILM VIDEO AND PHOTOGRAPHIC ARTS", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"STUDIO ARTS", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS FINE ARTS", 'category'=>"Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ENVIRONMENTAL SCIENCE", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"BIOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"BIOCHEMICAL SCIENCES", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"BOTANY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MOLECULAR BIOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ECOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GENETICS", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MICROBIOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHARMACOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHYSIOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ZOOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"NEUROSCIENCE", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS BIOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COGNITIVE SCIENCE AND BIOPSYCHOLOGY", 'category'=>"Biology & Life Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GENERAL BUSINESS", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ACCOUNTING", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ACTUARIAL SCIENCE", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"BUSINESS MANAGEMENT AND ADMINISTRATION", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"OPERATIONS LOGISTICS AND E-COMMERCE", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"BUSINESS ECONOMICS", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MARKETING AND MARKETING RESEARCH", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"FINANCE", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"HUMAN RESOURCES AND PERSONNEL MANAGEMENT", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INTERNATIONAL BUSINESS", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"HOSPITALITY MANAGEMENT", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MANAGEMENT INFORMATION SYSTEMS AND STATISTICS", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION", 'category'=>"Business", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMMUNICATIONS", 'category'=>"Communications & Journalism", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"JOURNALISM", 'category'=>"Communications & Journalism", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MASS MEDIA", 'category'=>"Communications & Journalism", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ADVERTISING AND PUBLIC RELATIONS", 'category'=>"Communications & Journalism", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMMUNICATION TECHNOLOGIES", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMPUTER AND INFORMATION SYSTEMS", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMPUTER PROGRAMMING AND DATA PROCESSING", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMPUTER SCIENCE", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INFORMATION SCIENCES", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMPUTER NETWORKING AND TELECOMMUNICATIONS", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MATHEMATICS", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"APPLIED MATHEMATICS", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"STATISTICS AND DECISION SCIENCE", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MATHEMATICS AND COMPUTER SCIENCE", 'category'=>"Computers & Mathematics", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GENERAL EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"EDUCATIONAL ADMINISTRATION AND SUPERVISION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SCHOOL STUDENT COUNSELING", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ELEMENTARY EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MATHEMATICS TEACHER EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHYSICAL AND HEALTH EDUCATION TEACHING", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"EARLY CHILDHOOD EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SCIENCE AND COMPUTER TEACHER EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SECONDARY TEACHER EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SPECIAL NEEDS EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"TEACHER EDUCATION: MULTIPLE LEVELS", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"LANGUAGE AND DRAMA EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ART AND MUSIC EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS EDUCATION", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"LIBRARY SCIENCE", 'category'=>"Education", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ARCHITECTURE", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GENERAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"AEROSPACE ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"BIOLOGICAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ARCHITECTURAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"BIOMEDICAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"CHEMICAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"CIVIL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMPUTER ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ELECTRICAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ENGINEERING MECHANICS PHYSICS AND SCIENCE", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ENVIRONMENTAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GEOLOGICAL AND GEOPHYSICAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INDUSTRIAL AND MANUFACTURING ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MATERIALS ENGINEERING AND MATERIALS SCIENCE", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MECHANICAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"METALLURGICAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MINING AND MINERAL ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"NAVAL ARCHITECTURE AND MARINE ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"NUCLEAR ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PETROLEUM ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS ENGINEERING", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ENGINEERING TECHNOLOGIES", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ENGINEERING AND INDUSTRIAL MANAGEMENT", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ELECTRICAL ENGINEERING TECHNOLOGY", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INDUSTRIAL PRODUCTION TECHNOLOGIES", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MECHANICAL ENGINEERING RELATED TECHNOLOGIES", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS ENGINEERING TECHNOLOGIES", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MATERIALS SCIENCE", 'category'=>"Engineering", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"NUTRITION SCIENCES", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GENERAL MEDICAL AND HEALTH SERVICES", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMMUNICATION DISORDERS SCIENCES AND SERVICES", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"HEALTH AND MEDICAL ADMINISTRATIVE SERVICES", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MEDICAL ASSISTING SERVICES", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MEDICAL TECHNOLOGIES TECHNICIANS", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"HEALTH AND MEDICAL PREPARATORY PROGRAMS", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"NURSING", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"TREATMENT THERAPY PROFESSIONS", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMMUNITY AND PUBLIC HEALTH", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS HEALTH MEDICAL PROFESSIONS", 'category'=>"Health", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"AREA ETHNIC AND CIVILIZATION STUDIES", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"OTHER FOREIGN LANGUAGES", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ENGLISH LANGUAGE AND LITERATURE", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COMPOSITION AND RHETORIC", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"LIBERAL ARTS", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"HUMANITIES", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INTERCULTURAL AND INTERNATIONAL STUDIES", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHILOSOPHY AND RELIGIOUS STUDIES", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"THEOLOGY AND RELIGIOUS VOCATIONS", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ANTHROPOLOGY AND ARCHEOLOGY", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ART HISTORY AND CRITICISM", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"HISTORY", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"UNITED STATES HISTORY", 'category'=>"Humanities & Liberal Arts", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COSMETOLOGY SERVICES AND CULINARY ARTS", 'category'=>"Industrial Arts & Consumer Services", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"FAMILY AND CONSUMER SCIENCES", 'category'=>"Industrial Arts & Consumer Services", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MILITARY TECHNOLOGIES", 'category'=>"Industrial Arts & Consumer Services", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHYSICAL FITNESS PARKS RECREATION AND LEISURE", 'category'=>"Industrial Arts & Consumer Services", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"CONSTRUCTION SERVICES", 'category'=>"Industrial Arts & Consumer Services", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ELECTRICAL,MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION",'category'=>"Industrial Arts & Consumer Services", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"TRANSPORTATION SCIENCES AND TECHNOLOGIES", 'category'=>"Industrial Arts & Consumer Services", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MULTI/INTERDISCIPLINARY STUDIES", 'category'=>"Interdisciplinary", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COURT REPORTING", 'category'=>"Law & Public Policy", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PRE-LAW AND LEGAL STUDIES", 'category'=>"Law & Public Policy", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"CRIMINAL JUSTICE AND FIRE PROTECTION", 'category'=>"Law & Public Policy", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PUBLIC ADMINISTRATION", 'category'=>"Law & Public Policy", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PUBLIC POLICY", 'category'=>"Law & Public Policy", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHYSICAL SCIENCES", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ASTRONOMY AND ASTROPHYSICS", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ATMOSPHERIC SCIENCES AND METEOROLOGY", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"CHEMISTRY", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GEOLOGY AND EARTH SCIENCE", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GEOSCIENCES", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"OCEANOGRAPHY", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PHYSICS", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MULTI-DISCIPLINARY OR GENERAL SCIENCE", 'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES",'category'=>"Physical Sciences", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"PSYCHOLOGY", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"EDUCATIONAL PSYCHOLOGY", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"CLINICAL PSYCHOLOGY", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"COUNSELING PSYCHOLOGY", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SOCIAL PSYCHOLOGY", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS PSYCHOLOGY", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"HUMAN SERVICES AND COMMUNITY ORGANIZATION", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SOCIAL WORK", 'category'=>"Psychology & Social Work", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INTERDISCIPLINARY SOCIAL SCIENCES", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GENERAL SOCIAL SCIENCES", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"ECONOMICS", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"CRIMINOLOGY", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"GEOGRAPHY", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"INTERNATIONAL RELATIONS", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"POLITICAL SCIENCE AND GOVERNMENT", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"SOCIOLOGY", 'category'=>"Social Science", 'modified_by'=>1]);
		DB::table('system_majors')->insert(['name'=>"MISCELLANEOUS SOCIAL SCIENCES", 'category'=>"Social Science", 'modified_by'=>1]);
 }
}
